### PR TITLE
Feature/users endpoints

### PR DESCRIPTION
**Pull request by toboid**
Ability to create and get a user. Not sure where we still store user info at the moment so keeping in memory.

Using [this](https://github.com/z0mt3c/hapi-swaggered) module for the swagger docs, seems to be working well so far and allows us to write the validation in Joi.

### CODE REVIEW

**Comment by brainsiq** [comment]
What do you think about using the responseValidation option from the swagger module? Seems to be something we were testing previously that's currently lost based on the change of module, unless I'm missing something somewhere (I can see the check for "is it documented"). Maybe using grunt-env to only enable it for tests?

**Comment by toboid** [comment]
Hapi validates the responses by default if a schema is set so any deviances from the docs will show up in testing. It's possible to configure Hapi to only validate  0-100% of responses and also whether to fail with a 500 or write to a log when the response validation fails. 

At the moment I've left response validation on for testing and when the api is running, as the overhead should be pretty low and and thought this is potentially an area where we don't want to accidentally leak attributes we didn't realise were being returned. Happy turn it off or log it for production though, and certainly think there will be other routes where we would want to do that.

**Comment by brainsiq** [comment]
Sweet, didn't know Hapi did that. I would think logging and alerting on that would probably be better in the long run to avoid breaking integrations?

**Comment by toboid** [comment]
Updated to make it configurable and log validation errors

**Pull request merged**
